"
I am an error. Oh no, if you are reading this, something terrible has happened!

Don't worry, I was raised because you asked a grammar to generate a tree with a maximum height
that is less than the minimum height among all trees it could generate. Just raise the maximum,
and this error will disappear.

As a side note, you can send the message `cost` to any grammar to get the minimum height a tree
it can generate will have.
"
Class {
	#name : #CostIsTooLow,
	#superclass : #Error,
	#category : #'Gnocco-Error'
}
